//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormularioPronostico.ServicioPronostico {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioPronostico.ServicioPronosticoSoap")]
    public interface ServicioPronosticoSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        FormularioPronostico.ServicioPronostico.HelloWorldResponse HelloWorld(FormularioPronostico.ServicioPronostico.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioPronostico.ServicioPronostico.HelloWorldResponse> HelloWorldAsync(FormularioPronostico.ServicioPronostico.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name SaludoPruebaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaludoPrueba", ReplyAction="*")]
        FormularioPronostico.ServicioPronostico.SaludoPruebaResponse SaludoPrueba(FormularioPronostico.ServicioPronostico.SaludoPruebaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaludoPrueba", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioPronostico.ServicioPronostico.SaludoPruebaResponse> SaludoPruebaAsync(FormularioPronostico.ServicioPronostico.SaludoPruebaRequest request);
        
        // CODEGEN: Generating message contract since element name ObtenerPronosticoPorFechaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPronosticoPorFecha", ReplyAction="*")]
        FormularioPronostico.ServicioPronostico.ObtenerPronosticoPorFechaResponse ObtenerPronosticoPorFecha(FormularioPronostico.ServicioPronostico.ObtenerPronosticoPorFechaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPronosticoPorFecha", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioPronostico.ServicioPronostico.ObtenerPronosticoPorFechaResponse> ObtenerPronosticoPorFechaAsync(FormularioPronostico.ServicioPronostico.ObtenerPronosticoPorFechaRequest request);
        
        // CODEGEN: Generating message contract since element name ObtenerPronosticosPorTemperaturaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPronosticosPorTemperatura", ReplyAction="*")]
        FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorTemperaturaResponse ObtenerPronosticosPorTemperatura(FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorTemperaturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPronosticosPorTemperatura", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorTemperaturaResponse> ObtenerPronosticosPorTemperaturaAsync(FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorTemperaturaRequest request);
        
        // CODEGEN: Generating message contract since element name ObtenerPronosticosPorProbabilidadLluviaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPronosticosPorProbabilidadLluvia", ReplyAction="*")]
        FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorProbabilidadLluviaResponse ObtenerPronosticosPorProbabilidadLluvia(FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorProbabilidadLluviaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPronosticosPorProbabilidadLluvia", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorProbabilidadLluviaResponse> ObtenerPronosticosPorProbabilidadLluviaAsync(FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorProbabilidadLluviaRequest request);
        
        // CODEGEN: Generating message contract since element name ObtenerTodosLosPronosticosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTodosLosPronosticos", ReplyAction="*")]
        FormularioPronostico.ServicioPronostico.ObtenerTodosLosPronosticosResponse ObtenerTodosLosPronosticos(FormularioPronostico.ServicioPronostico.ObtenerTodosLosPronosticosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTodosLosPronosticos", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioPronostico.ServicioPronostico.ObtenerTodosLosPronosticosResponse> ObtenerTodosLosPronosticosAsync(FormularioPronostico.ServicioPronostico.ObtenerTodosLosPronosticosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public FormularioPronostico.ServicioPronostico.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(FormularioPronostico.ServicioPronostico.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public FormularioPronostico.ServicioPronostico.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(FormularioPronostico.ServicioPronostico.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaludoPruebaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaludoPrueba", Namespace="http://tempuri.org/", Order=0)]
        public FormularioPronostico.ServicioPronostico.SaludoPruebaRequestBody Body;
        
        public SaludoPruebaRequest() {
        }
        
        public SaludoPruebaRequest(FormularioPronostico.ServicioPronostico.SaludoPruebaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaludoPruebaRequestBody {
        
        public SaludoPruebaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaludoPruebaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaludoPruebaResponse", Namespace="http://tempuri.org/", Order=0)]
        public FormularioPronostico.ServicioPronostico.SaludoPruebaResponseBody Body;
        
        public SaludoPruebaResponse() {
        }
        
        public SaludoPruebaResponse(FormularioPronostico.ServicioPronostico.SaludoPruebaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaludoPruebaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaludoPruebaResult;
        
        public SaludoPruebaResponseBody() {
        }
        
        public SaludoPruebaResponseBody(string SaludoPruebaResult) {
            this.SaludoPruebaResult = SaludoPruebaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPronosticoPorFechaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPronosticoPorFecha", Namespace="http://tempuri.org/", Order=0)]
        public FormularioPronostico.ServicioPronostico.ObtenerPronosticoPorFechaRequestBody Body;
        
        public ObtenerPronosticoPorFechaRequest() {
        }
        
        public ObtenerPronosticoPorFechaRequest(FormularioPronostico.ServicioPronostico.ObtenerPronosticoPorFechaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerPronosticoPorFechaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime fecha;
        
        public ObtenerPronosticoPorFechaRequestBody() {
        }
        
        public ObtenerPronosticoPorFechaRequestBody(System.DateTime fecha) {
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPronosticoPorFechaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPronosticoPorFechaResponse", Namespace="http://tempuri.org/", Order=0)]
        public FormularioPronostico.ServicioPronostico.ObtenerPronosticoPorFechaResponseBody Body;
        
        public ObtenerPronosticoPorFechaResponse() {
        }
        
        public ObtenerPronosticoPorFechaResponse(FormularioPronostico.ServicioPronostico.ObtenerPronosticoPorFechaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerPronosticoPorFechaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerPronosticoPorFechaResult;
        
        public ObtenerPronosticoPorFechaResponseBody() {
        }
        
        public ObtenerPronosticoPorFechaResponseBody(string ObtenerPronosticoPorFechaResult) {
            this.ObtenerPronosticoPorFechaResult = ObtenerPronosticoPorFechaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPronosticosPorTemperaturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPronosticosPorTemperatura", Namespace="http://tempuri.org/", Order=0)]
        public FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorTemperaturaRequestBody Body;
        
        public ObtenerPronosticosPorTemperaturaRequest() {
        }
        
        public ObtenerPronosticosPorTemperaturaRequest(FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorTemperaturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerPronosticosPorTemperaturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int temperatura;
        
        public ObtenerPronosticosPorTemperaturaRequestBody() {
        }
        
        public ObtenerPronosticosPorTemperaturaRequestBody(int temperatura) {
            this.temperatura = temperatura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPronosticosPorTemperaturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPronosticosPorTemperaturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorTemperaturaResponseBody Body;
        
        public ObtenerPronosticosPorTemperaturaResponse() {
        }
        
        public ObtenerPronosticosPorTemperaturaResponse(FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorTemperaturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerPronosticosPorTemperaturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerPronosticosPorTemperaturaResult;
        
        public ObtenerPronosticosPorTemperaturaResponseBody() {
        }
        
        public ObtenerPronosticosPorTemperaturaResponseBody(string ObtenerPronosticosPorTemperaturaResult) {
            this.ObtenerPronosticosPorTemperaturaResult = ObtenerPronosticosPorTemperaturaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPronosticosPorProbabilidadLluviaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPronosticosPorProbabilidadLluvia", Namespace="http://tempuri.org/", Order=0)]
        public FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorProbabilidadLluviaRequestBody Body;
        
        public ObtenerPronosticosPorProbabilidadLluviaRequest() {
        }
        
        public ObtenerPronosticosPorProbabilidadLluviaRequest(FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorProbabilidadLluviaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerPronosticosPorProbabilidadLluviaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double probabilidadLluvia;
        
        public ObtenerPronosticosPorProbabilidadLluviaRequestBody() {
        }
        
        public ObtenerPronosticosPorProbabilidadLluviaRequestBody(double probabilidadLluvia) {
            this.probabilidadLluvia = probabilidadLluvia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPronosticosPorProbabilidadLluviaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPronosticosPorProbabilidadLluviaResponse", Namespace="http://tempuri.org/", Order=0)]
        public FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorProbabilidadLluviaResponseBody Body;
        
        public ObtenerPronosticosPorProbabilidadLluviaResponse() {
        }
        
        public ObtenerPronosticosPorProbabilidadLluviaResponse(FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorProbabilidadLluviaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerPronosticosPorProbabilidadLluviaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerPronosticosPorProbabilidadLluviaResult;
        
        public ObtenerPronosticosPorProbabilidadLluviaResponseBody() {
        }
        
        public ObtenerPronosticosPorProbabilidadLluviaResponseBody(string ObtenerPronosticosPorProbabilidadLluviaResult) {
            this.ObtenerPronosticosPorProbabilidadLluviaResult = ObtenerPronosticosPorProbabilidadLluviaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTodosLosPronosticosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTodosLosPronosticos", Namespace="http://tempuri.org/", Order=0)]
        public FormularioPronostico.ServicioPronostico.ObtenerTodosLosPronosticosRequestBody Body;
        
        public ObtenerTodosLosPronosticosRequest() {
        }
        
        public ObtenerTodosLosPronosticosRequest(FormularioPronostico.ServicioPronostico.ObtenerTodosLosPronosticosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerTodosLosPronosticosRequestBody {
        
        public ObtenerTodosLosPronosticosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTodosLosPronosticosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTodosLosPronosticosResponse", Namespace="http://tempuri.org/", Order=0)]
        public FormularioPronostico.ServicioPronostico.ObtenerTodosLosPronosticosResponseBody Body;
        
        public ObtenerTodosLosPronosticosResponse() {
        }
        
        public ObtenerTodosLosPronosticosResponse(FormularioPronostico.ServicioPronostico.ObtenerTodosLosPronosticosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerTodosLosPronosticosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerTodosLosPronosticosResult;
        
        public ObtenerTodosLosPronosticosResponseBody() {
        }
        
        public ObtenerTodosLosPronosticosResponseBody(string ObtenerTodosLosPronosticosResult) {
            this.ObtenerTodosLosPronosticosResult = ObtenerTodosLosPronosticosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioPronosticoSoapChannel : FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPronosticoSoapClient : System.ServiceModel.ClientBase<FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap>, FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap {
        
        public ServicioPronosticoSoapClient() {
        }
        
        public ServicioPronosticoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPronosticoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPronosticoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPronosticoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioPronostico.ServicioPronostico.HelloWorldResponse FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap.HelloWorld(FormularioPronostico.ServicioPronostico.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            FormularioPronostico.ServicioPronostico.HelloWorldRequest inValue = new FormularioPronostico.ServicioPronostico.HelloWorldRequest();
            inValue.Body = new FormularioPronostico.ServicioPronostico.HelloWorldRequestBody();
            FormularioPronostico.ServicioPronostico.HelloWorldResponse retVal = ((FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioPronostico.ServicioPronostico.HelloWorldResponse> FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap.HelloWorldAsync(FormularioPronostico.ServicioPronostico.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioPronostico.ServicioPronostico.HelloWorldResponse> HelloWorldAsync() {
            FormularioPronostico.ServicioPronostico.HelloWorldRequest inValue = new FormularioPronostico.ServicioPronostico.HelloWorldRequest();
            inValue.Body = new FormularioPronostico.ServicioPronostico.HelloWorldRequestBody();
            return ((FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioPronostico.ServicioPronostico.SaludoPruebaResponse FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap.SaludoPrueba(FormularioPronostico.ServicioPronostico.SaludoPruebaRequest request) {
            return base.Channel.SaludoPrueba(request);
        }
        
        public string SaludoPrueba() {
            FormularioPronostico.ServicioPronostico.SaludoPruebaRequest inValue = new FormularioPronostico.ServicioPronostico.SaludoPruebaRequest();
            inValue.Body = new FormularioPronostico.ServicioPronostico.SaludoPruebaRequestBody();
            FormularioPronostico.ServicioPronostico.SaludoPruebaResponse retVal = ((FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap)(this)).SaludoPrueba(inValue);
            return retVal.Body.SaludoPruebaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioPronostico.ServicioPronostico.SaludoPruebaResponse> FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap.SaludoPruebaAsync(FormularioPronostico.ServicioPronostico.SaludoPruebaRequest request) {
            return base.Channel.SaludoPruebaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioPronostico.ServicioPronostico.SaludoPruebaResponse> SaludoPruebaAsync() {
            FormularioPronostico.ServicioPronostico.SaludoPruebaRequest inValue = new FormularioPronostico.ServicioPronostico.SaludoPruebaRequest();
            inValue.Body = new FormularioPronostico.ServicioPronostico.SaludoPruebaRequestBody();
            return ((FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap)(this)).SaludoPruebaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioPronostico.ServicioPronostico.ObtenerPronosticoPorFechaResponse FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap.ObtenerPronosticoPorFecha(FormularioPronostico.ServicioPronostico.ObtenerPronosticoPorFechaRequest request) {
            return base.Channel.ObtenerPronosticoPorFecha(request);
        }
        
        public string ObtenerPronosticoPorFecha(System.DateTime fecha) {
            FormularioPronostico.ServicioPronostico.ObtenerPronosticoPorFechaRequest inValue = new FormularioPronostico.ServicioPronostico.ObtenerPronosticoPorFechaRequest();
            inValue.Body = new FormularioPronostico.ServicioPronostico.ObtenerPronosticoPorFechaRequestBody();
            inValue.Body.fecha = fecha;
            FormularioPronostico.ServicioPronostico.ObtenerPronosticoPorFechaResponse retVal = ((FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap)(this)).ObtenerPronosticoPorFecha(inValue);
            return retVal.Body.ObtenerPronosticoPorFechaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioPronostico.ServicioPronostico.ObtenerPronosticoPorFechaResponse> FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap.ObtenerPronosticoPorFechaAsync(FormularioPronostico.ServicioPronostico.ObtenerPronosticoPorFechaRequest request) {
            return base.Channel.ObtenerPronosticoPorFechaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioPronostico.ServicioPronostico.ObtenerPronosticoPorFechaResponse> ObtenerPronosticoPorFechaAsync(System.DateTime fecha) {
            FormularioPronostico.ServicioPronostico.ObtenerPronosticoPorFechaRequest inValue = new FormularioPronostico.ServicioPronostico.ObtenerPronosticoPorFechaRequest();
            inValue.Body = new FormularioPronostico.ServicioPronostico.ObtenerPronosticoPorFechaRequestBody();
            inValue.Body.fecha = fecha;
            return ((FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap)(this)).ObtenerPronosticoPorFechaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorTemperaturaResponse FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap.ObtenerPronosticosPorTemperatura(FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorTemperaturaRequest request) {
            return base.Channel.ObtenerPronosticosPorTemperatura(request);
        }
        
        public string ObtenerPronosticosPorTemperatura(int temperatura) {
            FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorTemperaturaRequest inValue = new FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorTemperaturaRequest();
            inValue.Body = new FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorTemperaturaRequestBody();
            inValue.Body.temperatura = temperatura;
            FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorTemperaturaResponse retVal = ((FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap)(this)).ObtenerPronosticosPorTemperatura(inValue);
            return retVal.Body.ObtenerPronosticosPorTemperaturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorTemperaturaResponse> FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap.ObtenerPronosticosPorTemperaturaAsync(FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorTemperaturaRequest request) {
            return base.Channel.ObtenerPronosticosPorTemperaturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorTemperaturaResponse> ObtenerPronosticosPorTemperaturaAsync(int temperatura) {
            FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorTemperaturaRequest inValue = new FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorTemperaturaRequest();
            inValue.Body = new FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorTemperaturaRequestBody();
            inValue.Body.temperatura = temperatura;
            return ((FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap)(this)).ObtenerPronosticosPorTemperaturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorProbabilidadLluviaResponse FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap.ObtenerPronosticosPorProbabilidadLluvia(FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorProbabilidadLluviaRequest request) {
            return base.Channel.ObtenerPronosticosPorProbabilidadLluvia(request);
        }
        
        public string ObtenerPronosticosPorProbabilidadLluvia(double probabilidadLluvia) {
            FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorProbabilidadLluviaRequest inValue = new FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorProbabilidadLluviaRequest();
            inValue.Body = new FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorProbabilidadLluviaRequestBody();
            inValue.Body.probabilidadLluvia = probabilidadLluvia;
            FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorProbabilidadLluviaResponse retVal = ((FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap)(this)).ObtenerPronosticosPorProbabilidadLluvia(inValue);
            return retVal.Body.ObtenerPronosticosPorProbabilidadLluviaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorProbabilidadLluviaResponse> FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap.ObtenerPronosticosPorProbabilidadLluviaAsync(FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorProbabilidadLluviaRequest request) {
            return base.Channel.ObtenerPronosticosPorProbabilidadLluviaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorProbabilidadLluviaResponse> ObtenerPronosticosPorProbabilidadLluviaAsync(double probabilidadLluvia) {
            FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorProbabilidadLluviaRequest inValue = new FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorProbabilidadLluviaRequest();
            inValue.Body = new FormularioPronostico.ServicioPronostico.ObtenerPronosticosPorProbabilidadLluviaRequestBody();
            inValue.Body.probabilidadLluvia = probabilidadLluvia;
            return ((FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap)(this)).ObtenerPronosticosPorProbabilidadLluviaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioPronostico.ServicioPronostico.ObtenerTodosLosPronosticosResponse FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap.ObtenerTodosLosPronosticos(FormularioPronostico.ServicioPronostico.ObtenerTodosLosPronosticosRequest request) {
            return base.Channel.ObtenerTodosLosPronosticos(request);
        }
        
        public string ObtenerTodosLosPronosticos() {
            FormularioPronostico.ServicioPronostico.ObtenerTodosLosPronosticosRequest inValue = new FormularioPronostico.ServicioPronostico.ObtenerTodosLosPronosticosRequest();
            inValue.Body = new FormularioPronostico.ServicioPronostico.ObtenerTodosLosPronosticosRequestBody();
            FormularioPronostico.ServicioPronostico.ObtenerTodosLosPronosticosResponse retVal = ((FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap)(this)).ObtenerTodosLosPronosticos(inValue);
            return retVal.Body.ObtenerTodosLosPronosticosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioPronostico.ServicioPronostico.ObtenerTodosLosPronosticosResponse> FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap.ObtenerTodosLosPronosticosAsync(FormularioPronostico.ServicioPronostico.ObtenerTodosLosPronosticosRequest request) {
            return base.Channel.ObtenerTodosLosPronosticosAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioPronostico.ServicioPronostico.ObtenerTodosLosPronosticosResponse> ObtenerTodosLosPronosticosAsync() {
            FormularioPronostico.ServicioPronostico.ObtenerTodosLosPronosticosRequest inValue = new FormularioPronostico.ServicioPronostico.ObtenerTodosLosPronosticosRequest();
            inValue.Body = new FormularioPronostico.ServicioPronostico.ObtenerTodosLosPronosticosRequestBody();
            return ((FormularioPronostico.ServicioPronostico.ServicioPronosticoSoap)(this)).ObtenerTodosLosPronosticosAsync(inValue);
        }
    }
}
