//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormularioSERECU.ServiciosSERECU {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosSERECU.ServicioSERECUSoap")]
    public interface ServicioSERECUSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        FormularioSERECU.ServiciosSERECU.HelloWorldResponse HelloWorld(FormularioSERECU.ServiciosSERECU.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioSERECU.ServiciosSERECU.HelloWorldResponse> HelloWorldAsync(FormularioSERECU.ServiciosSERECU.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name ci from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        FormularioSERECU.ServiciosSERECU.ObtenerDatosResponse ObtenerDatos(FormularioSERECU.ServiciosSERECU.ObtenerDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioSERECU.ServiciosSERECU.ObtenerDatosResponse> ObtenerDatosAsync(FormularioSERECU.ServiciosSERECU.ObtenerDatosRequest request);
        
        // CODEGEN: Generating message contract since element name ci from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoNacimiento", ReplyAction="*")]
        FormularioSERECU.ServiciosSERECU.ObtenerCertificadoNacimientoResponse ObtenerCertificadoNacimiento(FormularioSERECU.ServiciosSERECU.ObtenerCertificadoNacimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoNacimiento", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioSERECU.ServiciosSERECU.ObtenerCertificadoNacimientoResponse> ObtenerCertificadoNacimientoAsync(FormularioSERECU.ServiciosSERECU.ObtenerCertificadoNacimientoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public FormularioSERECU.ServiciosSERECU.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(FormularioSERECU.ServiciosSERECU.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public FormularioSERECU.ServiciosSERECU.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(FormularioSERECU.ServiciosSERECU.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatos", Namespace="http://tempuri.org/", Order=0)]
        public FormularioSERECU.ServiciosSERECU.ObtenerDatosRequestBody Body;
        
        public ObtenerDatosRequest() {
        }
        
        public ObtenerDatosRequest(FormularioSERECU.ServiciosSERECU.ObtenerDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public ObtenerDatosRequestBody() {
        }
        
        public ObtenerDatosRequestBody(string ci) {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public FormularioSERECU.ServiciosSERECU.ObtenerDatosResponseBody Body;
        
        public ObtenerDatosResponse() {
        }
        
        public ObtenerDatosResponse(FormularioSERECU.ServiciosSERECU.ObtenerDatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerDatosResult;
        
        public ObtenerDatosResponseBody() {
        }
        
        public ObtenerDatosResponseBody(string ObtenerDatosResult) {
            this.ObtenerDatosResult = ObtenerDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoNacimientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoNacimiento", Namespace="http://tempuri.org/", Order=0)]
        public FormularioSERECU.ServiciosSERECU.ObtenerCertificadoNacimientoRequestBody Body;
        
        public ObtenerCertificadoNacimientoRequest() {
        }
        
        public ObtenerCertificadoNacimientoRequest(FormularioSERECU.ServiciosSERECU.ObtenerCertificadoNacimientoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoNacimientoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public ObtenerCertificadoNacimientoRequestBody() {
        }
        
        public ObtenerCertificadoNacimientoRequestBody(string ci) {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoNacimientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoNacimientoResponse", Namespace="http://tempuri.org/", Order=0)]
        public FormularioSERECU.ServiciosSERECU.ObtenerCertificadoNacimientoResponseBody Body;
        
        public ObtenerCertificadoNacimientoResponse() {
        }
        
        public ObtenerCertificadoNacimientoResponse(FormularioSERECU.ServiciosSERECU.ObtenerCertificadoNacimientoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoNacimientoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerCertificadoNacimientoResult;
        
        public ObtenerCertificadoNacimientoResponseBody() {
        }
        
        public ObtenerCertificadoNacimientoResponseBody(string ObtenerCertificadoNacimientoResult) {
            this.ObtenerCertificadoNacimientoResult = ObtenerCertificadoNacimientoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioSERECUSoapChannel : FormularioSERECU.ServiciosSERECU.ServicioSERECUSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSERECUSoapClient : System.ServiceModel.ClientBase<FormularioSERECU.ServiciosSERECU.ServicioSERECUSoap>, FormularioSERECU.ServiciosSERECU.ServicioSERECUSoap {
        
        public ServicioSERECUSoapClient() {
        }
        
        public ServicioSERECUSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSERECUSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSERECUSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSERECUSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioSERECU.ServiciosSERECU.HelloWorldResponse FormularioSERECU.ServiciosSERECU.ServicioSERECUSoap.HelloWorld(FormularioSERECU.ServiciosSERECU.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            FormularioSERECU.ServiciosSERECU.HelloWorldRequest inValue = new FormularioSERECU.ServiciosSERECU.HelloWorldRequest();
            inValue.Body = new FormularioSERECU.ServiciosSERECU.HelloWorldRequestBody();
            FormularioSERECU.ServiciosSERECU.HelloWorldResponse retVal = ((FormularioSERECU.ServiciosSERECU.ServicioSERECUSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioSERECU.ServiciosSERECU.HelloWorldResponse> FormularioSERECU.ServiciosSERECU.ServicioSERECUSoap.HelloWorldAsync(FormularioSERECU.ServiciosSERECU.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioSERECU.ServiciosSERECU.HelloWorldResponse> HelloWorldAsync() {
            FormularioSERECU.ServiciosSERECU.HelloWorldRequest inValue = new FormularioSERECU.ServiciosSERECU.HelloWorldRequest();
            inValue.Body = new FormularioSERECU.ServiciosSERECU.HelloWorldRequestBody();
            return ((FormularioSERECU.ServiciosSERECU.ServicioSERECUSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioSERECU.ServiciosSERECU.ObtenerDatosResponse FormularioSERECU.ServiciosSERECU.ServicioSERECUSoap.ObtenerDatos(FormularioSERECU.ServiciosSERECU.ObtenerDatosRequest request) {
            return base.Channel.ObtenerDatos(request);
        }
        
        public string ObtenerDatos(string ci) {
            FormularioSERECU.ServiciosSERECU.ObtenerDatosRequest inValue = new FormularioSERECU.ServiciosSERECU.ObtenerDatosRequest();
            inValue.Body = new FormularioSERECU.ServiciosSERECU.ObtenerDatosRequestBody();
            inValue.Body.ci = ci;
            FormularioSERECU.ServiciosSERECU.ObtenerDatosResponse retVal = ((FormularioSERECU.ServiciosSERECU.ServicioSERECUSoap)(this)).ObtenerDatos(inValue);
            return retVal.Body.ObtenerDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioSERECU.ServiciosSERECU.ObtenerDatosResponse> FormularioSERECU.ServiciosSERECU.ServicioSERECUSoap.ObtenerDatosAsync(FormularioSERECU.ServiciosSERECU.ObtenerDatosRequest request) {
            return base.Channel.ObtenerDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioSERECU.ServiciosSERECU.ObtenerDatosResponse> ObtenerDatosAsync(string ci) {
            FormularioSERECU.ServiciosSERECU.ObtenerDatosRequest inValue = new FormularioSERECU.ServiciosSERECU.ObtenerDatosRequest();
            inValue.Body = new FormularioSERECU.ServiciosSERECU.ObtenerDatosRequestBody();
            inValue.Body.ci = ci;
            return ((FormularioSERECU.ServiciosSERECU.ServicioSERECUSoap)(this)).ObtenerDatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioSERECU.ServiciosSERECU.ObtenerCertificadoNacimientoResponse FormularioSERECU.ServiciosSERECU.ServicioSERECUSoap.ObtenerCertificadoNacimiento(FormularioSERECU.ServiciosSERECU.ObtenerCertificadoNacimientoRequest request) {
            return base.Channel.ObtenerCertificadoNacimiento(request);
        }
        
        public string ObtenerCertificadoNacimiento(string ci) {
            FormularioSERECU.ServiciosSERECU.ObtenerCertificadoNacimientoRequest inValue = new FormularioSERECU.ServiciosSERECU.ObtenerCertificadoNacimientoRequest();
            inValue.Body = new FormularioSERECU.ServiciosSERECU.ObtenerCertificadoNacimientoRequestBody();
            inValue.Body.ci = ci;
            FormularioSERECU.ServiciosSERECU.ObtenerCertificadoNacimientoResponse retVal = ((FormularioSERECU.ServiciosSERECU.ServicioSERECUSoap)(this)).ObtenerCertificadoNacimiento(inValue);
            return retVal.Body.ObtenerCertificadoNacimientoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioSERECU.ServiciosSERECU.ObtenerCertificadoNacimientoResponse> FormularioSERECU.ServiciosSERECU.ServicioSERECUSoap.ObtenerCertificadoNacimientoAsync(FormularioSERECU.ServiciosSERECU.ObtenerCertificadoNacimientoRequest request) {
            return base.Channel.ObtenerCertificadoNacimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioSERECU.ServiciosSERECU.ObtenerCertificadoNacimientoResponse> ObtenerCertificadoNacimientoAsync(string ci) {
            FormularioSERECU.ServiciosSERECU.ObtenerCertificadoNacimientoRequest inValue = new FormularioSERECU.ServiciosSERECU.ObtenerCertificadoNacimientoRequest();
            inValue.Body = new FormularioSERECU.ServiciosSERECU.ObtenerCertificadoNacimientoRequestBody();
            inValue.Body.ci = ci;
            return ((FormularioSERECU.ServiciosSERECU.ServicioSERECUSoap)(this)).ObtenerCertificadoNacimientoAsync(inValue);
        }
    }
}
